### ISSUE TITLE
Publish to PowershellGallery.com

### ISSUE THREAD

**Issue by ChrisLGardner** [pcgeek86/cADFS#5]
I've got a number of projects where having this module available in the gallery would be great, particularly for pulling down the latest version as part of an automated build. 

Any chance that could be done?

**Comment by cwegener** [comment]
I agree. Publishing to PSGallery would be useful and would make installation much easier.

**Comment by ChrisLGardner** [comment]
After a quick conversation with Trevor on Twitter I'm going to publish to the gallery and continue development in my fork. I'll link to there in the module manifest but I'll keep Trevor attributed as the original author. 

I should hopefully have something published to the gallery in the next few days.

**Comment by ChrisLGardner** [comment]
It's now in the gallery and links back to my repo. I'll pull in your changes to it and see if I can get a new version published in the next day or so. https://www.powershellgallery.com/packages/cADFS/1.1.0.0

I'm also looking at putting in some unit tests and appveyor support like the main DSC resources just to streamline everything.
