### ISSUE TITLE
Add Feature to allow managing of SAMLEndpoints for Relying Party trusts.

### ISSUE THREAD

**Issue by cwegener** [pcgeek86/cADFS#6]
I would like to manage SAMLEndpoints in addition to the WS-Federation endpoints.

**Comment by hackjammer** [comment]
@pcgeek86 - this PR seems to have been merged in the version on PSGallery - can you merge it back to github please?

**Comment by ChrisLGardner** [comment]
It's available in my fork: https://github.com/ChrisLGardner/cADFS
________________________________

**Comment by pcgeek86** [comment]
Sorry for the delay -- merged. Thanks for your contribution @cwegener. #7
